# render.yaml
# Corrected version for deploying a FastAPI backend and Streamlit frontend.

services:
  # ---- Backend Service (FastAPI) ----
  - type: web
    name: bot-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    # Runs backend.py; assumes your FastAPI app instance is named 'app'
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10 # Or your desired Python version

  # ---- Frontend Service (Streamlit) ----
  - type: web
    name: bot-frontend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    # Runs frontend.py
    startCommand: "streamlit run frontend.py --server.port $PORT --server.headless true"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10 # Or your desired Python version
      # --- FIX IS HERE ---
      # We now construct the internal URL for the backend service.
      # Render services can talk to each other using their name as the hostname.
      # The default internal port for web services is 10000.
      - key: BACKEND_URL
        value: http://bot-backend:10000/chat

